# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef815bfa6af6a7c4694f8ca7c53e46371d286417b95db1594fa1aea0e98e7f378252c472dab330e10523031ddab0c8923aa7321d99a90cc941c459c87af4388a

test:
  secret_key_base: 286b140e25aaa977fd2f88c397823354988cc78543c7b9dbe97e776672a952835daad1f217ef9ae0de1985a5e0d5e9dbc8a29fd3ce1f0c80f741809b73f30405

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
